Repository openebs/mayastor, pull requests merged in 2024-06, with the labels that each got.

#1666 Update documentation URL in README.md
  README.md
Labels: documentation

#1671 chore: update file metadata Dockerfile
  Dockerfile
Labels: Tech debt, Project grooming

#1675 chore: force date metadata update on LICENSE file
  LICENSE
Labels: Ready for review, not a defect, Tech debt, Project grooming

#1680 chore: new Mayastor contributing.md
  CONTRIBUTING.md
Labels: Ready for review, Tech debt
